version: "3.9"

services:
  gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${gatewayPORT}:3000"
    depends_on:
      - user_service
      - merchant_service
      - order_service
      - payment_service
      - drone_delivery_service
    volumes:
      - ./backend/gateway:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - USER_SERVICE_URL=http://user_service:${userServicePORT}
      - MERCHANT_SERVICE_URL=http://merchant_service:${merchantServicePORT}
      - ORDER_SERVICE_URL=http://order_service:${orderServicePORT}
      - PAYMENT_SERVICE_URL=http://payment_service:${paymentServicePORT}
      - DRONE_DELIVERY_SERVICE_URL=http://drone_delivery_service:${droneDeliveryServicePORT}
    networks:
      - app-network

  user_service:
    build:
      context: ./backend/userService
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${userServicePORT}:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL_USER}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - postgres
    volumes:
      - ./backend/userService:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
  
  merchant_service:
    build:
      context: ./backend/merchantService
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${merchantServicePORT}:3002"
      - "50051:50051"
    environment:
      - DATABASE_URL=${DATABASE_URL_MERCHANT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - GRPC_PORT=50051
    depends_on:
      - postgres
    volumes:
      - ./backend/merchantService:/app
      - /app/node_modules
      - ./backend/proto:/app/proto
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  order_service:
    build:
      context: ./backend/orderService
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${orderServicePORT}:3003"
    environment:
      - DATABASE_URL=${DATABASE_URL_ORDER}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - MERCHANT_GRPC_URL=merchant_service:50051
    depends_on:
      - postgres
      - merchant_service
    volumes:
      - ./backend/orderService:/app
      - /app/node_modules
      - ./backend/proto:/app/proto
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    
  payment_service:
    build:
      context: ./backend/paymentService
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${paymentServicePORT}:3004"
    environment:
      - DATABASE_URL=${DATABASE_URL_PAYMENT}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - postgres
    volumes:
      - ./backend/paymentService:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  drone_delivery_service:
    build:
      context: ./backend/droneDeliveryService
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${droneDeliveryServicePORT}:3005"
    environment:
      - DATABASE_URL=${DATABASE_URL_DRONE_DELIVERY}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - postgres
    volumes:
      - ./backend/droneDeliveryService:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${frontendPORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://gateway:3000
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: pgdb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
      - PGTZ=${PGTZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rbmq
    # restart: always
    ports:
      - "${rabbitMQ_PORT}:5672"     
      - "${rabbitMQ_UI_PORT}:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER} 
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network  

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok/ngrok.yml"
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok/ngrok.yml
    ports:
      - "4040:4040"
    depends_on:
      - payment_service
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
